import json
import os

SEVERITY_MAP = {
    0: "MEDIUM",    # Walkway violation — policy says WARNING
    1: "CRITICAL",  # Unauthorized intervention — CRITICAL SAFETY NOTICE
    2: "MEDIUM",    # Open panel cover — policy says WARNING
    3: "CRITICAL",  # Forklift overload — CRITICAL SAFETY NOTICE
}

ESCALATION_MAP = {
    "LOW":      "Logged to DB",
    "MEDIUM":   "Logged to DB",
    "HIGH":     "Real-time alert triggered + DB log",
    "CRITICAL": "Real-time alert triggered + DB log",
}


def assign_severity(detection: dict) -> dict:
    class_id = detection.get("class_id", -1)
    severity = SEVERITY_MAP.get(class_id, "LOW")

    # Upgrade MEDIUM to HIGH if confidence is high
    if severity == "MEDIUM" and detection.get("confidence") == "high":
        severity = "HIGH"

    detection["severity"] = severity
    detection["escalation_action"] = ESCALATION_MAP[severity]
    return detection


def process_all(input_path: str, output_path: str) -> list:
    with open(input_path) as f:
        detections = json.load(f)

    for d in detections:
        assign_severity(d)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(detections, f, indent=2)

    counts = {}
    for d in detections:
        s = d["severity"]
        counts[s] = counts.get(s, 0) + 1

    print("Severity summary:")
    for sev, n in sorted(counts.items()):
        print(f"  {sev}: {n} violation(s)")

    print(f"Saved → {output_path}")
    return detections


if __name__ == "__main__":
    # FIX: Point to the raw detections generated by the video engine
    process_all(
        "outputs/raw_detections.json",
        "outputs/violations_with_severity.json"
    )